- uses: koki-develop/hub-purge-action@v1
  with:
    repository: koki-develop/koki-develop
    branch: main
    path: path/to/README.md
    # path: |
    #   path/to/README.md
    #   path/to/README.ja.md
