name: Purge Hub Cache

on:
  push:
    branches: [main]
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: koki-develop/hub-purge-action@v1.0.3
        with:
          repository: koki-develop/koki-develop
          branch: main
          path: path/to/README.md